### ISSUE TITLE
Remove the input lag

### ISSUE THREAD

**Issue by pavelbat3** [G4me4u/g4mespeed#12]

**Comment by G4me4u** [comment]
What input lag?

**Comment by pavelbat3** [comment]
when I slow down the time to about 0.5 tps and put blocks, there is a delay after clicking the mouse https://modrinth.com/mod/no-lag-tickratechanger - here is a mod that does not have this, but this mod is only up to version 1.17

**Comment by pavelbat3** [comment]
![AjiiBZL](https://github.com/G4me4u/g4mespeed/assets/99824228/e9364e11-d7c8-4ea5-b3ba-63e83fdcd85c)
only in this gif video (it's not mine) your ex is on the left, I took this gif video from here - https://modrinth.com/mod/no-lag-tickratechanger

**Comment by pavelbat3** [comment]
> What input lag?
approximately 0.3 seconds at a 0.2 tps deceleration
I'm sorry, I'm not English and when you asked "what input lag" I thought you were asking about what input lag is, I'm sorry

**Comment by G4me4u** [comment]
Have you tried enabling Fixed Movement Speed in the client settings? This resolves the issue.

**Comment by pavelbat3** [comment]
this makes the player move as if the tps is at 20, and I would like the player to move with the tps that I set

**Comment by G4me4u** [comment]
As it stands right now I don't see a good use case for that. What do you intend to use it for?

**Comment by pavelbat3** [comment]
maybe a TAS

**Comment by G4me4u** [comment]
I thought so. But then it is no longer theoretically possible in vanilla since you are placing more than 20 blocks per in-game second.

This feature would not be eligible for a TAS, but rather for cheating or modded behavior.
