### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by SirCatCat** [G4me4u/g4mespeed#14]
When you use G4mespeed and the Essential mod in the 1.21 your game crashes

**Comment by G4me4u** [comment]
Can you confirm whether this fixes the issue?

[g4mespeed-1.4.6-mc1.21.1.zip](https://github.com/user-attachments/files/16805604/g4mespeed-1.4.6-mc1.21.1.zip)

Just unzip and use the mod.

**Comment by SirCatCat** [comment]
Now it is alright thanks.

**Comment by G4me4u** [comment]
Fixed in v1.4.7-mc1.21.1
