### ISSUE TITLE
[1.19.4]Rendering bug when shader is enabled

### ISSUE THREAD

**Issue by Niu-se** [G4me4u/g4mespeed#5]
https://user-images.githubusercontent.com/34495930/227752006-7a62223b-7ad3-427d-9097-289b1776a412.mp4

It works fine when the shader is disabled.But piston disappear when the shader is enabled and the piston is moving.

https://user-images.githubusercontent.com/34495930/227752430-b8cfe606-24df-400b-b46d-d58874602c57.mp4

Exception, it works ture if I don't stay stationary.
I think this is a bug.
mod list:
![p1](https://user-images.githubusercontent.com/34495930/227752804-ec61b5b1-9cdd-4108-8f45-9ed374f8b3f4.png)
fabric 0.14.18
java 17.0.6
shader:
- BSL_v8.2.02
- ComplementaryShaders_v4.7.1

**Comment by G4me4u** [comment]
Thanks for the report! Very detailed :-)

I can reproduce with Iris and Sodium installed. Seems to happen both with and without G4mespeed, so I do not think it is related to G4mespeed. Therefore, I think this issue is better posted in their repository.
