### ISSUE TITLE
Crash on 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [G4me4u/g4mespeed#9]
https://pastebin.com/raw/iPfTwQEp

I updated to Fabric loader 0.15.0 and using API version 0.91.1.
On the Client side everything loads fine.

**Comment by sternschnaube** [comment]
Thank you 😊

**Comment by G4me4u** [comment]
You are welcome. It is annoying that fabric-loader seemed to be the issue. It has never happened previously, and I didn't change my code in that regard. If anything like this happens again, please reach out :)

**Comment by sternschnaube** [comment]
Thank you, from my experience, the loader was just 2-3 times the problem.
